name: location_formatter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  cloud_firestore: ^5.5.0
  firebase_core: ^3.8.0
  cupertino_icons: ^1.0.8

flutter:
  uses-material-design: true
  assets:
    - assets/shivansh.jpg

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
